name: Release my application
on: [push]
jobs:
  StaticCodeAnalysis:
    runs-on: ubuntu-latest
    steps:
      - run: echo "static code analysis"
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - 
        name: try to compile
        run: mvn compile
      - 
        name: run my tests
        run: mvn test
  ReleaseMyApp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - run: mvn package
      - run: ls -la target/
      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "target/my-ecommerce-0.1.jar"
          body: my first release
          name: My pre release for ecommerce application
