name: Run tests
on: [push]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - run: echo "perform static code"
  RunMyUnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn test
  ReleaMyApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Mavern package
        run: mvn package -DskipTests
      - name: list compiled files
        run: ls -la target/
    
